version: '3.8'

services:
  web:
    build: ./php
    container_name: php_app
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: adatok
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "7260:3306"
    networks:
      - appnet
    volumes:
      - ./php/init.sql:/docker-entrypoint-initdb.d/init.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "7281:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "7280:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - web
    networks:
      - appnet

networks:
  appnet:
